Make it solid

diff --git a/.github/workflows/check-links-in-prod.yaml b/.github/workflows/check-links-in-prod.yaml
--- a/.github/workflows/check-links-in-prod.yaml
+++ b/.github/workflows/check-links-in-prod.yaml
@@ -18,7 +18,7 @@ jobs:
             ghcr.io/linkchecker/linkchecker:latest \
             https://docs.giantswarm.io/overview/ \
             --check-extern \
-            -t 1 -r 2
+            -t 1 -r 2 || echo "failed1=true" >> "$GITHUB_ENV"
         continue-on-error: true
 
       - name: check-links-in-getting-started-pages
@@ -27,7 +27,7 @@ jobs:
             ghcr.io/linkchecker/linkchecker:latest \
             https://docs.giantswarm.io/getting-started/ \
             --check-extern \
-            -t 1 -r 2
+            -t 1 -r 2 || echo "failed2=true" >> "$GITHUB_ENV"
         continue-on-error: true
 
       - name: check-links-in-tutorials-pages
@@ -36,7 +36,7 @@ jobs:
             ghcr.io/linkchecker/linkchecker:latest \
             https://docs.giantswarm.io/tutorials/ \
             --check-extern \
-            -t 1 -r 2
+            -t 1 -r 2 || echo "failed3=true" >> "$GITHUB_ENV"
         continue-on-error: true
 
       - name: check-links-in-reference-pages
@@ -45,7 +45,7 @@ jobs:
             ghcr.io/linkchecker/linkchecker:latest \
             https://docs.giantswarm.io/reference/ \
             --check-extern \
-            -t 1 -r 2
+            -t 1 -r 2 || echo "failed4=true" >> "$GITHUB_ENV"
         continue-on-error: true
 
       - name: check-links-in-support-pages
@@ -54,7 +54,7 @@ jobs:
             ghcr.io/linkchecker/linkchecker:latest \
             https://docs.giantswarm.io/support/ \
             --check-extern \
-            -t 1 -r 2
+            -t 1 -r 2 || echo "failed5=true" >> "$GITHUB_ENV"
         continue-on-error: true
 
       - name: check-links-in-changelogs
@@ -67,4 +67,29 @@ jobs:
             --ignore-url="^https://.*example\.com/.*" \
             --ignore-url="^https://my-org\.github\.com/.*" \
             --ignore-url="^https://github\.com/giantswarm/giantswarm/.*" \
-            --ignore-url=".*gigantic\.io.*"
+            --ignore-url=".*gigantic\.io.*" || echo "failed6=true" >> "$GITHUB_ENV"
+        continue-on-error: true
+
+      - name: Report errors
+        run: |
+          if [[ $failed1 == "true" ]]; then
+            echo "There has been some errors in overview checks"
+          fi
+          if [[ $failed2 == "true" ]]; then
+            echo "There has been some errors in getting started checks"
+          fi
+          if [[ $failed3 == "true" ]]; then
+            echo "There has been some errors in tutorials checks"
+          fi
+          if [[ $failed4 == "true" ]]; then
+            echo "There has been some errors in reference checks"
+          fi
+          if [[ $failed5 == "true" ]]; then
+            echo "There has been some errors in support checks"
+          fi
+          if [[ $failed6 "true" ]]; then
+            echo "There has been some errors in changelogs checks"
+          fi
+          if [[ $failed1 == "true" ]] || [[ $failed1 }}" == "true" ]] || [[ $failed1 == "true" ]] || [[ $failed1 == "true" ]] || [[ $failed1 == "true" ]] || [[ $failed1 "true" ]]; then
+            exit 1
+          fi
