Write HTML reports, store as artifacts

diff --git a/.github/workflows/check-links-in-prod.yaml b/.github/workflows/check-links-in-prod.yaml
--- a/.github/workflows/check-links-in-prod.yaml
+++ b/.github/workflows/check-links-in-prod.yaml
@@ -9,7 +9,7 @@ jobs:
   check-links:
     runs-on: ubuntu-latest
     steps:
-      - name: Pull images
+      - name: Pull image
         run: docker pull ghcr.io/linkchecker/linkchecker:latest
 
       - name: check-links-in-overview-pages
@@ -18,7 +18,11 @@ jobs:
             ghcr.io/linkchecker/linkchecker:latest \
             https://docs.giantswarm.io/overview/ \
             --check-extern \
-            -t 1 -r 2 || echo "failed1=true" >> "$GITHUB_ENV"
+            --threads 1 \
+            --recursion-level 2 \
+            --no-status \
+            --file-output html/utf8/overview.html \
+            || echo "failed1=true" >> "$GITHUB_ENV"
         continue-on-error: true
 
       - name: check-links-in-getting-started-pages
@@ -27,7 +31,11 @@ jobs:
             ghcr.io/linkchecker/linkchecker:latest \
             https://docs.giantswarm.io/getting-started/ \
             --check-extern \
-            -t 1 -r 2 || echo "failed2=true" >> "$GITHUB_ENV"
+            --threads 1 \
+            --recursion-level 2 \
+            --no-status \
+            --file-output html/utf8/getting-started.html \
+            || echo "failed2=true" >> "$GITHUB_ENV"
         continue-on-error: true
 
       - name: check-links-in-tutorials-pages
@@ -36,7 +44,11 @@ jobs:
             ghcr.io/linkchecker/linkchecker:latest \
             https://docs.giantswarm.io/tutorials/ \
             --check-extern \
-            -t 1 -r 2 || echo "failed3=true" >> "$GITHUB_ENV"
+            --threads 1 \
+            --recursion-level 2 \
+            --no-status \
+            --file-output html/utf8/tutorials.html \
+            || echo "failed3=true" >> "$GITHUB_ENV"
         continue-on-error: true
 
       - name: check-links-in-reference-pages
@@ -45,7 +57,11 @@ jobs:
             ghcr.io/linkchecker/linkchecker:latest \
             https://docs.giantswarm.io/reference/ \
             --check-extern \
-            -t 1 -r 2 || echo "failed4=true" >> "$GITHUB_ENV"
+            --threads 1 \
+            --recursion-level 2 \
+            --no-status \
+            --file-output html/utf8/reference.html \
+             || echo "failed4=true" >> "$GITHUB_ENV"
         continue-on-error: true
 
       - name: check-links-in-support-pages
@@ -54,7 +70,11 @@ jobs:
             ghcr.io/linkchecker/linkchecker:latest \
             https://docs.giantswarm.io/support/ \
             --check-extern \
-            -t 1 -r 2 || echo "failed5=true" >> "$GITHUB_ENV"
+            --threads 1 \
+            --recursion-level 2 \
+            --no-status \
+            --file-output html/utf8/support.html \
+            || echo "failed5=true" >> "$GITHUB_ENV"
         continue-on-error: true
 
       - name: check-links-in-changelogs
@@ -62,14 +82,26 @@ jobs:
           docker run --rm --name linkchecker \
             ghcr.io/linkchecker/linkchecker:latest \
             https://docs.giantswarm.io/changes/ \
-            -t 1 -r 2 \
+            --threads 1 \
+            --recursion-level 2 \
+            --no-status \
+            --file-output html/utf8/changes.html \
             --ignore-url="^https://github.com/giantswarm/docs/.*" \
             --ignore-url="^https://.*example\.com/.*" \
             --ignore-url="^https://my-org\.github\.com/.*" \
             --ignore-url="^https://github\.com/giantswarm/giantswarm/.*" \
-            --ignore-url=".*gigantic\.io.*" || echo "failed6=true" >> "$GITHUB_ENV"
+            --ignore-url=".*gigantic\.io.*" \
+            || echo "failed6=true" >> "$GITHUB_ENV"
         continue-on-error: true
 
+      - name: Store reports as artifacts
+        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.2
+        with:
+          name: link-check-reports
+          path: "."
+          if-no-files-found: warn
+          retention-days: 14
+      
       - name: Report errors
         run: |
           if [[ $failed1 == "true" ]]; then
