Removing all references to api-spec (#2450)

diff --git a/.github/workflows/validate.yaml b/.github/workflows/validate.yaml
--- a/.github/workflows/validate.yaml
+++ b/.github/workflows/validate.yaml
@@ -26,8 +26,11 @@ jobs:
             # Print for debugging
             printf "\nAnnotations JSON:\n"
             cat ./annotations.json
+
             # Save as environment variable for next step
-            echo "found_front_matter_issues=true" >> $GITHUB_ENV
+            if [ $(jq length < ./annotations.json) -gt 0 ]; then
+              echo "found_front_matter_issues=true" >> $GITHUB_ENV
+            fi
           fi
           rm files.txt
 
@@ -58,8 +61,9 @@ jobs:
           printf "\nAnnotations JSON:\n"
           cat ./markdownlint-annotations.json
           
-          # Save as environment variable for next step
-          echo "found_markdown_issues=true" >> $GITHUB_ENV
+          if [ $(jq length < ./markdownlint-annotations.json) -gt 0 ]; then
+            echo "found_markdown_issues=true" >> $GITHUB_ENV
+          fi
 
       - name: Send markdownlint annotations
         if: ${{ env.found_markdown_issues == 'true' }}
@@ -70,12 +74,10 @@ jobs:
           input: ./markdownlint-annotations.json
 
       - name: Fail if markdownlint had findings
+        if: ${{ env.found_markdown_issues == 'true' }}
         run: |
-          # If there are non-empty lines, we had linting findings
-          if [ "$(awk 1 < markdownlint.out | wc -l | awk '{print $1}')" != 0 ]; then
-            echo "ERROR: See markdownlint findings (annotated as errors in the PR when you click on 'Files changed')"
-            exit 1
-          fi
+          echo "ERROR: See markdownlint findings (annotated as errors in the PR when you click on 'Files changed')"
+          exit 1
 
       - name: Check file and folder names in content
         shell: python {0}
