Attempt to fix workflow

diff --git a/.github/workflows/validate.yaml b/.github/workflows/validate.yaml
--- a/.github/workflows/validate.yaml
+++ b/.github/workflows/validate.yaml
@@ -70,12 +70,10 @@ jobs:
           input: ./markdownlint-annotations.json
 
       - name: Fail if markdownlint had findings
+        if: ${{ env.found_markdown_issues == 'true' }}
         run: |
-          # If there are non-empty lines, we had linting findings
-          if [ "$(awk 1 < markdownlint.out | wc -l | awk '{print $1}')" != 0 ]; then
-            echo "ERROR: See markdownlint findings (annotated as errors in the PR when you click on 'Files changed')"
-            exit 1
-          fi
+          echo "ERROR: See markdownlint findings (annotated as errors in the PR when you click on 'Files changed')"
+          exit 1
 
       - name: Check file and folder names in content
         shell: python {0}
